require("config.lazy")
require("config.opts")
require("config.keys")
require("config.autocmds")

require("config.lsp.luals")
require("config.lsp.zls")
require("config.lsp.ty")
require("config.lsp.ruff")
require("config.lsp.pyright")
require("config.lsp.pylsp")
